portfolio/urls.py
from django.urls import path
from .views import home, skills, contact_view, about

app_name = 'portfolio'
urlpatterns = [
    path('', home, name='home'),
    path('skills/', skills, name='skills'),
    path('contact/', contact_view, name='contact'),
    path('about/', about, name='about'),
]

portfolionthumo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('__reload__', include('django_browser_reload.urls')),
    path('', include('portfolio.urls')),
    path('admin/', admin.site.urls),
]

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Your Name', 'class': 'form-input bg-black border border-gray-600 rounded-lg w-full p-2 text-white'})
        )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'placeholder': 'Your Email', 'class': 'form-input bg-black border border-gray-600 rounded-lg w-full p-2 text-white'})
        )
    comment = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Message', 'class': 'form-textarea bg-black border border-gray-600 rounded-lg w-full p-2 text-white h-20'})
        )

portfolio/views.py
from django.shortcuts import render,redirect
from django.core.mail import send_mail
from django.conf import settings
from .forms import ContactForm
import logging


logger = logging.getLogger(__name__)

#homeview
def home(request):
    return render(request, 'portfolio/home.html')

#aboutview
def about(request):
    return render(request, 'portfolio/about.html')

#skillsview
def skills(request):
    return render(request, 'portfolio/skills.html')


#contactformview
def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            comment = form.cleaned_data['comment']
            try:
                send_mail(
                    f"New contact form submission from {name}",
                    comment,
                    email,
                    [settings.DEFAULT_FROM_EMAIL],
                    fail_silently=False,
                )
                return redirect('contact')
            except Exception as e:
                logger.error(f"Error Sending Email: {e}")
                return render(request, 'portfolio/contact.html', {'form':form, 'error': 'There was an error sending your message. Please try later.'})
    else:
        form = ContactForm()

    return render(request, 'portfolio/contact.html', {'form': form})

portfolio/templates/portfolio/about.html
{% extends 'portfolio/base.html'%}
{% load static %}

{% block title %}About{% endblock %}

{% block content %}
<div class="bg-zinc-900 h-full">
    <div class="grid container mx-auto gap-4 pt-4">
        <div class="text-center text-white text-4xl md:text-4xl lg:text-5xl bg-zinc-800 h-40 flex items-center justify-center rounded-lg">
            <h1 class="flex items-center gap-4 underline underline-offset-8 decoration-sky-700 pt-4">
                <img src="{% static 'images/me' %}" alt="Nthumo" class="border-4 rounded-full border-gray-300 shadow-lg" style="width: 120px; height: 120px;">
                <span class="text-gray-300">WHO I <span class="text-sky-700">AM?</span> </span>
                
            </h1>
        </div>
        <div class="flex text-white text-wrap bg-zinc-800 p-4 md:p-20 rounded-lg whitespace-normal text-left h-full">          
            <div class="text-wrap">
                <p class="mb-4">
                    Hi, I'm Emmanuel Nthumo Mutinda, a passionate full-stack software developer with a strong foundation in Python and other programming languages. Currently, I am pursuing my Bachelor's degree in Computer Science at Murang'a University of Technology.
                    As a full-stack developer, I am proficient in a variety of technologies and tools. My expertise includes Python, Django, JavaScript, React, HTML, CSS, and SQL. <!-- I have successfully completed several projects, including Project 1, Project 2, and Project 3, which demonstrate my ability to build robust and scalable web applications.-->
                    I am particularly interested in developing innovative solutions that leverage modern technologies to solve real-world problems. 
                </p>
                <p>
                    My goal is to continually improve my skills and contribute to impactful projects in the tech industry. I am eager to collaborate with like-minded professionals and organizations that share my passion for technology and innovation.
                    Beyond my technical abilities, I am known for my strong problem-solving skills, attention to detail, and ability to work effectively in team settings. I am always eager to learn new technologies and stay updated with industry trends.
                    Thank you for visiting my portfolio. Feel free to explore my projects and get in touch with me if you'd like to discuss potential opportunities or collaborations.
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

portfolio/templates/portfolio/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} Title {% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/dist/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/dist/anime.css' %}">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    {% block head %}{% endblock %}

</head>
<body class="bg-black overflow-auto text-center h-svh">
    {% block content %} {% endblock %}
</body>
</html>

portfolio/templates/portfolio/contact.html
{%extends 'portfolio/base.html'%}
{% load static %}
{% block title %}Contact{% endblock %}

{% block content %}
<div class="bg-zinc-900 text-white h-full">
    <div class="grid grid-cols-1 gap-4 md:grid-cols-2 px-4 py-8">
        <div class="max-w-lg mx-auto p-8 rounded-lg bg-zinc-800 items-center grid gap-y-4 pt-2">
            <div>
                <img src="{%static 'images/lapi'%}" alt="Laptop" class="rounded-lg" style="width: 450px; height: 250px;">
            </div>
            <div class="bg-zinc-900 h-50 md:h-40 rounded-lg p-4">
                <h1>If you have any suggestions, project ideas or even just want to say Hello, feel free to reach out.</h1>
                <br>
                <h1 class="text-orange-400">Click the icon of your choice and you'll find me there:</h1>
            </div>
            <div class="flex gap-4 items-center justify-center bg-white p-2 rounded-lg bottom-0">
                <a href="https://github.com/Nthumo"><img src="{%static 'images/github'%}" width="35" alt="github" class=""></a>
                <a href="https://x.com/1_nthumo"><img src="{% static 'images/X'%}" width="35" alt="X" class="rounded-full"></a>
                <a href="https://wa.me/+254797575799"><img src="{%static 'images/whatsapp'%}" width="35" alt="whatsapp"></a>
                <a href="tel:+254797575799"><img src="{%static 'images/phone'%}" width="35" alt="phone" class="rounded-full"></a>
            </div>
        </div>

        <div class="max-w-lg mx-auto bg-zinc-800 p-8 rounded-lg shadow-lg">
            <h2 class="md:text-2xl font-bold mb-4 text-white underline underline-offset-8 decoration-double decoration-sky-400">DROP ME A LINE</h2>
            <p class="mb-4">And if you'd like to reach out through email you can do so by filling out this form:</p>
            <form method="post">
                {% csrf_token %}
                <div class="mb-4">
                    <label for="name" class="sr-only"></label>
                    {{ form.name }}
                </div>
                <div class="mb-4">
                    <label for="email" class="sr-only"></label>
                    {{ form.email }}
                </div>
                <div class="mb-4">
                    <label for="comment" class="sr-only"></label>
                    {{ form.comment }}
                </div>
                <button type="submit" class="bg-sky-400 text-white py-2 px-4 rounded-lg hover:bg-sky-600 hover:border">
                        <span class="text-black font-bold">SEND MESSAGE</span>
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html'%}
{% block title %}Nthumo{% endblock %}

{% block head %}
    <style>
        .group:hover .hover-text-white {
            color: rgb(31, 10, 224)
        }
        .group:hover .hover-text-black {
            color: #FFFFFF;
        }

        .bebas-neue-regular {
         font-family: "Bebas Neue", sans-serif;
         font-weight: 400;
         font-style: normal;
        }
    </style>
{% endblock %}

{% block content %}
<div class="overflow-hidden">
    <div class="flex flex-col p-4 h-svh">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-2 h-full w-full">
            <!-- intro section-->
            <div class="p-4 sm:p-6 md:p-8 lg:10 xl:12 flex flex-col justify-center items-center sm:min-h-[150px] min-h-[100px] md:min-h-[200px] gap-4">
                <p class="block text-gray-300 text-lg md:text-2xl lg:text-3xl">HI THERE! I'M</p>
                <h1 class="block text-2xl md:text-4xl lg:5xl font-serif font-extrabold text-center text-sky-400">NTHUMO MUTINDA</h1>
                <div class="wrapper">
                    <h1 class="overflow-hidden text-wrap block font-mono font-extrabold text-md md:text-lg lg:text-xl text-center pt-2">
                        <span class="word block text-white">SOFTWARE DEVELOPER</span>
                        <span class="word block text-white opacity-25 line-through decoration-red-600">ANIMATOR</span>
                        <span class="word block text-white">SOFTWARE DEVELOPER</span>
                        <span class="word block text-white">GRAPHIC DESIGNER</span>
                        <span class="word block text-white opacity-25 line-through decoration-red-600">VIDEO EDITOR</span>
                    </h1>
                </div>
            </div>

            <!--about section-->
            <a href="{% url 'portfolio:about'%}" class="md:l-10 rounded bg-zinc-900 p-4 sm:p-6 md:p-8 lg:p-10 xl:p-12 flex items-center justify-center sm:min-h-[80px] min-h-[100px] md:min-h-[200px] group transform transition-all cursor-pointer hover:scale-95">
                <div class="">
                    <h2 class="text-2xl md:text-4xl font-extrabold text-center text-white">
                        <span class="hover-text-white">ABOUT</span>
                        <span class="hover-text-black text-blue-800">ME</span>
                    </h2>
                </div>
            </a>

            <!-- my skills section-->
            <a href="{% url 'portfolio:skills'%}" class="rounded bg-zinc-900 p-4 sm:p-6 md:p-8 lg:p-10 xl:p-12 flex items-center justify-center sm:min-h-[80px] min-h-[100px] md:min-h-[200px] group transition-all transform cursor-pointer hover:scale-95">
                <div  class="" >
                    <h2 class="text-2xl md:text-4xl font-extrabold text-center text-white">
                        <span class="hover-text-white">MY</span>
                        <span class="text-blue-800 hover-text-black">SKILLS</span>
                    </h2>
                    <h2 class="text-2xl font-bold text-white">(Projects)</h2>
                </div>
            </a>
             

            <!-- get in touch section-->
            <a href="{% url 'portfolio:contact' %}" class="rounded bg-zinc-900 p-4 sm:p-6 md:p-8 lg:p-10 xl:p-12 flex items-center justify-center sm:min-h-[80px] min-h-[100px] md:min-h-[200px] group transition-all cursor-pointer hover:scale-95 transform">
                <div class="">
                    <h2 class="text-2xl md:text-4xl font-extrabold text-center text-white">
                        <span class="hover-text-white">GET</span>
                        <span class="text-blue-800 hover-text-black">IN TOUCH</span>
                    </h2>
                </div>
            </a>
        </div>
    </div>
</div>
{% endblock %}

portfolio/templates/portfolio/skills.html
{% extends 'portfolio/base.html'%}
{% load static %}
{% block title %}Skills{% endblock %}

{% block head%}
   <style>
        .custom-header {
            display: inline-block;
            width: max-content;
        }
        .project-item {
            cursor: pointer;
        }
        .project-details {
            position: relative;
            overflow: hidden;
            display: none;
        }
        .project-details.active {
            display: block;
        }
        .project-details:hover .overlay {
            opacity: 1;
        }
        .project-details:hover .blur-effect {
            filter: blur(4px);
            transform: scale(1.05);
        }
        .blur-effect {
            transition: all 0.3s ease;
        }

    </style>
{% endblock %}

{% block content %}
<div class="bg-zinc-900 p-4 overflow-auto">
    <div class="mb-12">
        <h1 class="text-white font-bold text-4xl italic underline">Projects</h1>
    </div>

    <!--Projects names-->
    <div class="md:flex grid place-items-center md:items-center space-x-8 md:justify-center">
        <div class=" space-y-4 md:w-[300px] max-w-lg">
            <div id="project-1" class="md:absolute top-28 bg-zinc-800 p-4 w-[220px] left-[100px] rounded-xl hover:bg-black border project-item active">
                <h1 class="text-white">Restaurant Application</h1>
            </div>
            <div id="project-2" class="md:absolute top-44 bg-zinc-800 p-4 w-[220px] left-[100px] rounded-xl hover:bg-black border project-item">
                <h1 class="text-white text-sm md:text-xl">A Reservation System</h1>
            </div>
        </div>
    
        <!--Project details-->
        <div class="container mx-auto md:w-[800px] w-auto md:h-[500px] md:mt-0 mt-8 rounded-xl bg-white p-4">
            <div id="details-project-1" class="project-details blur-effect active">
                <img src="{% static 'images/resto.png' %}" alt="Restaurant Application" class="mt- rounded-lg">
                <div class=" mt-12 left-20">
                    <div class="flex flex-col gap-2">
                        <div class="bg-gray-400 p-1 rounded-xl text-gray-800 w-[100px] border-gray-900">
                            <h1>Django</h1>
                        </div>
                        <div class="bg-gray-400 p-1 rounded-xl text-gray-800 w-[100px] border-black">
                            <h1>React</h1> 
                        </div>
                    </div>
                </div>
                <div class="absolute right-[5px] md:right-[300px] bottom-10 md:bottom-2">
                    <a href="https://restaurantapp-l2q9ftapd-nthumos-projects.vercel.app/" target="_blank">
                        <div class="bg-zinc-900  md:w-auto w-[100px] hover:cursor text-white hover:text-black p-1 md:p-2 flex gap-x-2 rounded-xl hover:bg-gray-200 hover:border border-black">
                            <img src="{%static 'images/right.png'%}" width="20" alt="arrow">
                            <h1>Website</h1>
                        </div>
                    </a>
                </div>
                <div class="absolute right-[5px] w-auto md:right-[200px] bottom-0 md:bottom-2">
                    <a href="https://github.com/Nthumo/restaurant-fullstack-app" target="_blank">
                        <div class="bg-zinc-900  md:w-auto w-[100px] hover:cursor text-white hover:text-black p-1 md:p-2 flex gap-x-2 rounded-xl hover:bg-gray-200 hover:border border-black">
                            <img src="{%static 'images/github'%}" width="20" alt="github">
                            <h1>GitHub</h1>
                        </div>
                    </a> 
                </div>
            </div>
            <div id="details-project-2" class="project-details bg-gray-200 p-4 rounded-xl">
                <h1 class="font-bold">I'm currently working on this project. The project will be available soon.</h1>
                <span>Thank you for your interest on this Project.</span>
            </div>
        </div>
    </div>

    <div class="mt-[50px]">
        <h1 class="text-4xl text-white font-bold italic underline">Skills</h1>
    </div>

    <div class="grid md:grid-cols-2 gap-4 mt-[50px]">
        <!--programming languages-->
        <div class="bg-zinc-800 min-h-[100px] text-white text-center rounded-lg">
            <h1>
                <span class="underline-offset-8 decoration-double decoration-sky-400 underline text-white">LANGUAGES</span>
                <ol class="grid gap-2 pt-4 p-4 ">
                    <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                        <img src="{% static 'images/python' %}" width="30" alt="python">
                        Python
                    </li>
                    <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                        <img src="{% static 'images/js' %}" width="30" alt="JavaScript" class="rounded-lg">
                        JavaScript
                    </li>
                    <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                        <img src="{%static 'images/c'%}" width="30" alt="C">
                        C/C++
                    </li>
                    <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                        <img src="{%static 'images/html5'%}" width="30" alt="HTML">
                        HTML
                    </li>
                        
                    <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                        <img src="{%static 'images/css3'%}" width="30" alt="HTML">
                        CSS
                    </li>
                    
                    <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                        <img src="{%static 'images/sql'%}" width="50" alt="">
                        SQL
                    </li>
                </ol>
                
            </h1>

        </div>

        <!--frameworks and libraries-->
        <div class="bg-zinc-800 min-h-[100px] text-white text-center rounded-lg">
            <h1>
                <span class="underline-offset-8 decoration-double decoration-sky-400 underline text-white">FRAMEWORKS AND LIBRARIES</span>
                <ol class="grid gap-2 pt-4 p-4">
                    <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                        <img src="{%static 'images/django'%}" width="30" alt="django" class="rounded-lg">
                        Django
                    </li>
                    <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                        <img src="{%static 'images/react.png'%}" width="30" alt="react" class="rounded-lg">
                        React
                    </li>
                    <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                        <img src="{%static 'images/tailwind'%}" width="30" alt="tailwindcss">
                        Tailwind CSS
                    </li>
                </ol>
            </h1>
        </div>

        <!--databases-->
        <div class="bg-zinc-800 min-h-[100px] text-white text-center rounded-lg">
            <h1>
                <span class="text-white underline decoration-double decoration-sky-400 underline-offset-8">DATABASES</span>
                <ol class="grid gap-2 pt-4 p-4">
                    <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                        <img src="{%static 'images/postgresql'%}" width="30" alt="PostreSQL">
                        PostreSQL
                    </li>
                    <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                        <img src="{%static 'images/sqlite'%}" width="30" alt="SQLite">
                        SQLite
                    </li>
                    <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                        <img src="{%static 'images/mongodb'%}" width="15" alt="MongoDB">
                        MongoDB
                    </li>
                </ol>
                
            </h1>
        </div>

        <!--apis and web services-->
        <div class="bg-zinc-800 min-h-[100px] text-white text-center rounded-lg">
            <h1>
                <span class="text-white underline underline-offset-8 decoration-double decoration-sky-400">APIs AND WEB SERVICES</span>
                <ol class="grid gap-2 pt-4 p-4">
                    <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">Django REST framework</li>
                    <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                        <img src="{%static 'images/graphql'%}" width="30" alt="graphql">
                        GraphQl
                    </li>
                </ol>
            </h1>
        </div>

        <!--version control and collaboration-->
        <div class="bg-zinc-800 min-h-[100px] h-40 text-white text-center rounded-lg">
            <h1>
                <span class="underline underline-offset-8 decoration-double decoration-sky-400">VERSION CONTROL AND COLLABORATION</span>
                <ol class="grid gap-2 pt-4 p-4">
                    <li class="flex gap-4 items-center block p-2 bg-zinc-900 hover:border rounded-lg">
                        <img src="{%static 'images/git'%}" width="30" alt="Git" class="rounded-lg">
                        Git
                    </li>
                    <li class="flex gap-4 items-center block p-2 bg-zinc-900 hover:border rounded-lg">
                        <img src="{%static 'images/github'%}" width="30" alt="">
                        GitHub
                    </li>
                </ol>
            </h1>
        </div>

        <!--development tools-->
        <div class="bg-zinc-800 min-h-[100px] text-white text-center rounded-lg">
            <h1 class="">
                <span class="underline underline-offset-8 decoration-double decoration-sky-400">DEVELOPMENT TECHNOLOGIES</span>
                <ol class="grid gap-2 pt-4 p-4">
                    <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                        <img src="{%static 'images/docker'%}" width="30" alt="Docker">
                        Docker
                    </li>
                    <li class="flex gap-4 items-center block p-2 bg-black hover:border rounded-lg">
                        <img src="{%static 'images/kubernetes'%}" width="30" alt="Kubernetes">
                        Kubernetes
                    </li>
                </ol>
            </h1>
        </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function () {

        const projectItems = document.querySelectorAll('.project-item');
        const projectDetails = document.querySelectorAll('.project-details');

        projectItems.forEach(item => {
            item.addEventListener('click', function() {
                //Remove active class form all projects items and details
                projectItems.forEach(i => i.classList.remove('active'));
                projectDetails.forEach(d => d.classList.remove('active'));

                // Add active class to the clicked projects and the corresponding details
                this.classList.add('active');
                document.querySelector('#details-' + this.id).classList.add('active');
            });
        });
    });
</script>
{% endblock %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>